### ISSUE TITLE
Mouse follow shrinking the powertip even if the smart placement is set to true

### ISSUE THREAD

**Issue by TheNaoX** [stevenbenner/jquery-powertip#128]
That happens when the powertip area is next to a browser edge

![Example](http://s12.postimg.org/lgkwl9ojx/Screen_Shot_2015_01_05_at_3_03_29_PM.png)

**Comment by stevenbenner** [comment]
You probably want to have a fixed width, or at least minimum width on tooltips that you don't want to shrink in tight spaces. See the [docs for fixed width CSS](https://stevenbenner.github.io/jquery-powertip/#fixed-width). Alternatively, since you might want this tooltip to be elastic to a point you could set the `min-width` CSS rule.

**Comment by TheNaoX** [comment]
Yeah that did the trick, thanks a lot for the answer!
