### ISSUE TITLE
Zooming

### ISSUE THREAD

**Issue by PewienTyp** [stevenbenner/jquery-powertip#129]
not work correctly when i change zoom of html

**Comment by stevenbenner** [comment]
What browser are you using? I cannot reproduce this on the latest Firefox, Chrome, or Internet Explorer.

**Comment by PewienTyp** [comment]
i using chrome v40

**Comment by stevenbenner** [comment]
The current stable release for Chrome is 39. I take it you're on the beta?

What operating system are you using? I could download the beta version and see if I can reproduce the issue.

**Comment by PewienTyp** [comment]
os: windows 7
In different version than beta is the same.
on 100% is
![100%](http://i.imgur.com/S6K2dMZ.png)

in 120% is
![120%](http://i.imgur.com/bFQpSZH.png)

**Comment by stevenbenner** [comment]
I tested the [project page](http://stevenbenner.github.io/jquery-powertip) and my edge case suite in both Chrome 39 and 40 on Windows 7, they both work as expected when zoomed.

Can you put an example document up on the web or [JSFiddle](http://jsfiddle.net/)?

**Comment by stevenbenner** [comment]
There has been no response for an extended period of time.  Closing issue.

**Comment by rbrlortie** [comment]
I get the same issue when applying the zoom via CSS.

body.addAccessibility { zoom:1.25; }

**Comment by stevenbenner** [comment]
@rbrlortie, what browser are you using? If it's a specific set of recent chrome versions (45+ I believe) then you might be experiencing bug #153. That's due to be fixed soonish.

If it's another browser then it might be this original bug, which I was never able to reproduce. Let me know the browser, browser version, and operating system that you're using.

**Comment by rbrlortie** [comment]
Hi @stevenbenner, 

Thanks for the quick answer.

I know that it happen on both of those versions of chrome: 
- Version 61.0.3163.100 (Official Build) (64-bit)
- Version 62.0.3202.89 (Official Build) (64-bit)

At first I thought that the problem was that the CSS zoom was applied to the whole body but the issue persists even when moving it to a specific div.
