### ISSUE TITLE
Sometimes the arrow doesn't render properly, or align properly

### ISSUE THREAD

**Issue by vincentwansink** [stevenbenner/jquery-powertip#132]
I'm not sure if it's an alignment issue, but it seems completely random.  I am using Google Chrome.  Not sure if it does it in other browsers.  Sometimes I just need to reload the page and it renders properly, sometimes I need to reload the page several times to fix it.  See images.

This is what it should look like every time.
![powertip good](https://cloud.githubusercontent.com/assets/1832248/6259081/039da8a0-b78c-11e4-9439-c18751c35b6d.jpg)

But sometimes it looks like this.
![powertip bad](https://cloud.githubusercontent.com/assets/1832248/6259080/039ca46e-b78c-11e4-8db0-b81972470f89.jpg)

**Comment by stevenbenner** [comment]
That looks like there might be other CSS affecting the tooltip div. Inspect it with dev tools, especially the ":before" pseudo and see if there is any other styles being applied.

If you can put an example somewhere I can try to debug it for you.

**Comment by stevenbenner** [comment]
Closing this issues because there is not enough information to do any debugging.

**Comment by vincentwansink** [comment]
As an alternative to figuring out what's causing the arrow alignment issue, is it possible for me to hide the arrow altogether?  

I continue to have this issue on most pages where I use powertip.  It will render properly when the page first loads, but I noticed that if I have many powertips and hover from one to the other, the rendering starts to mess up.  In this example the arrow is on top of the tooltip, hiding some of the text.

![tooltip](https://cloud.githubusercontent.com/assets/1832248/10711793/4349f88e-7a44-11e5-972c-846c856d7fcc.png)

I would prefer to have no arrow on the speech bubble at all, rather than have the arrow render in the wrong position.  Is this an available option?  And if not, is there an easy way for me to make it so?

**Comment by stevenbenner** [comment]
There isn't a specific option to remove the arrow, but that's because it is pure CSS. You can remove the arrow from the CSS by deleting everything in the CSS file after the `#powerTip { /* ... */ }` block.

The selected lines in [this example](https://github.com/stevenbenner/jquery-powertip/blob/dc5972bcbbd4229043bb1cf42ab7004c8846277e/css/jquery.powertip.css#L20-L99) are all for the arrows. They can be deleted if you don't want any arrows.

If you can provide me with a working example or at least a screenshot of the dev tools CSS for the tooltip element I could try to figure out what's going on.

**Comment by vincentwansink** [comment]
Thanks for that.  I've been trying to determine the exact sequence of events that lead to the problem but so far it just seems completely random.  If I can figure out how to reproduce it I'll send you something to look at.
