### ISSUE TITLE
Re-initializing PowerTip on an element breaks functionality

### ISSUE THREAD

**Issue by juhana** [stevenbenner/jquery-powertip#157]
If you initialize PowerTip twice:

```
$('#test').powerTip();
$('#test').powerTip();
```

...the functionality breaks: the tooltip doesn't appear anymore. If you initialize a third time it works again and so on, so it works as a toggle.

Sometimes you do things like `$('.one').powerTip(); $('.two').powerTip();` which breaks all elements that have both classes, so calling `.powerTip()` twice should be allowed. Optimally re-initializing should remove the old binding and re-attach with the new options.

**Comment by ntzm** [comment]
Would like to see a fix for this. For the time being I'm using this workaround:

```js
function addTooltips() {
    $images = $('img');
    $images.not('.powertip-rendered').powerTip();
    $images.addClass('powertip-rendered');
}
```

and calling `addTooltips()` when I add new images.

**Comment by stevenbenner** [comment]
This should be fixed with commit 1ca1102e1ee01b2e6ec7b919e3dd4a6699675325.

This was actually the result of two logic bugs with the similar effects. Basically the previous state of the tooltip system would affect the next call, leading to a failure on any even number of reinitialization attempts.

* **The PowerTip data attributes were loaded before the `destroy()` call on initialization.**
     If the element previously had been set up by PowerTip, then the check for the usage of the `title` HTML attribute would fail because it would think that one of the other PowerTip data attributes was already populated. This would cause the tooltip system to not find any content for the tooltip if it was using the HTML `title` attribute as the data source. In which case it would simply abort on open because there's no point in showing an empty tooltip.

    The fix for this is to make sure that we don't load the data attributes until after `destroy()` is called.

    This bug has been present since 1.2.0. I'm surprised that no one reported it until now.

* **The `TooltipController` was instantiated before the `destroy()` call on initialization.**
    The `destroy()` API method was improved to remove the tooltip element(s) if all PowerTip instances had been destroyed. And the `TooltipController` is responsible for building the tooltip element. So in this case, if you called `powerTip()` twice, and that was the only PowerTip instance on the page then the tooltip element would be removed and the events unhooked immediately after they were built.

    The fix for this is to make sure that we don't instantiate the `TooltipController` until after `destroy()` is called.

    This bug has been present since 1.3.0, which was just recently released.

Thank you for finding this bug and reporting it to me! The fix will go out with the next PowerTip release.

**Comment by sura2k** [comment]
@stevenbenner will there be a new release soon? last one (1.3.0) was about a year ago unless I'm looking at a wrong release page.

**Comment by stevenbenner** [comment]
@sura2k, yes, there will be a new release in the near future. I have been planning to publish the next version since January, but I keep finding little things I need to tweak. Right now there is only one issue left to work on in the [1.3.1 milestone](https://github.com/stevenbenner/jquery-powertip/milestone/5), so hopefully I'll be able to release it in the next month or so.
