### ISSUE TITLE
Why does PT remove the title attribute?

### ISSUE THREAD

**Issue by avrij-brandon** [stevenbenner/jquery-powertip#164]
When a PT tool tip is initialized the title attribute is remove form the element. I imagine it's because the browser would show it's own tool-tip and interfere with PT. True?

**Comment by stevenbenner** [comment]
That is correct. This is done because browsers will show native tooltips for anything with a `title` attribute. So if the mouse cursor hovered over an element with both a PowerTip tooltip and a `title` attribute the user would see two tooltips at the same time.

The way PowerTip works is that the content of the `title` attribute it moved to a jQuery `.data()` attribute ("powertip"). If PowerTip is `destroy()`ed on the element via the API then it will reset the `title` attribute to the original state.

**Comment by stevenbenner** [comment]
Seems that the question has been answered satisfactorily. Closing issue.

If you have any follow-up questions then please feel free to ask.
