### ISSUE TITLE
Support multiple tooltips to be shown in the screen

### ISSUE THREAD

**Issue by sura2k** [stevenbenner/jquery-powertip#168]
Scenario:  With `manual` (Assume all are manual tooltips)
Triggers: show/hide on mouse enter
When mouse enters to element X, its tooltip bubbles up. When mouse moves to element Y, tooltip of Y should bubble up and it does. But it doesn't mean that tooptip of X should be vanished or relocate for Y.

Actually `manual` option should be able to show multiple tooltips at the same time.
When I debug, I found that only one tooltip container is available and therefore it won't work so this is the design. But do you have any plan to support multiple tooltips to be able to visible at the same time?

**Comment by stevenbenner** [comment]
Probably not, but you might be able to convince me to add support if there's a really good reason.

One of the original design goals I had was to [make web site tooltips that behave like desktop tooltips](https://github.com/stevenbenner/jquery-powertip/blob/master/doc/README.md#design-goals). Part of that was that only one tooltip would be visible at a time.

There has been interest in supporting multiple tooltips before, and someone actually put together [a way to do it in one scenario](https://stackoverflow.com/a/13943497). But no one has really provided a compelling use-case that makes it worth the effort. From a user experience perspective, if the user is seeing multiple active tooltips then it's probably difficult to interact with.

What are you trying to do that needs to show more than one tooltip at a time?

**Comment by stevenbenner** [comment]
There hasn't been any interest in this issue in a long time, and the request kind of goes against the design goals. So I'm closing this.

**Comment by suranga-nibaya** [comment]
@stevenbenner sorry... 
I think I have missed your initial reply. I don't remember what I was trying to do, but anyway since you have asked a use case, I will give one.

As I remember I was started to using this on a web application. And this has lots of drag and drop components. These components are same but they have different tags. If a user has added more components or editing an existing board, user needs a clear picture (roughly eye catching) of how many are their under category one, category two, etc and whether he/she has missing any required components in the board. So these "required" components are decided by the user at that time, therefore hard a give a validation, but yes slightly we can give a hint.. 

I don't remember exact business use case, but this was the idea. Also I don't remember whether I made any changes to your code to get it done, or went with some other tool tip solution. Most probably I must have picked a different one since I have mentioned in the issue that the modification I was expecting is not supported because of the design...which is again as per my understanding at that time.

Hope you have some idea for future references.
Thank you!
