### ISSUE TITLE
bower: keep built version in vcs?

### ISSUE THREAD

**Issue by tony** [stevenbenner/jquery-powertip#54]
https://github.com/twitter/bower/issues/150

I'm trying to user jquery-powertip via bower. Any chance we can have a built version kept in repository?

**Comment by jgable** [comment]
I've also ran into this issue and decided to fork and publish as [jquery-powertip-dist](https://github.com/jgable/jquery-powertip/blob/master/bower.json) with the dist files checked in and all others ignored.  

If you see anything about the package that you'd like me to update (I wasn't sure about the license, but did put a link to your original project in the description) feel free to comment here or open a PR in the fork.

I'll try to pull your changes in and rebuild whenever a release is pushed; if you @tag me in a comment when you release that would make it easier.  Otherwise, I'll just try to keep an eye out.
